name: "Problem, or a bug"
description: If you have a problem, bug, or enhancement with a resource in this resource module.

body:
  - type: markdown
    attributes:
      value: |
        Your feedback and support is greatly appreciated, thanks for contributing!
        Thank you for opening an issue. Please fill in the following information to help us triage (and fix) your issue.

  - type: textarea
    attributes:
      label: "Description of the issue"
      description: |
        Details of the scenario you tried and the problem that is occurring

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

